#!/bin/bash

# shellcheck disable=SC2046
export $(grep -v '^#' .env | xargs)

echo "----------------"
docker run -d \
    --name kafka-container \
    -p ${KAFKA_PORT}:${KAFKA_PORT} \
    -e KAFKA_NODE_ID=${KAFKA_NODE_ID} \
    -e KAFKA_LISTENERS=${KAFKA_LISTENERS} \
    -e KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS} \
    -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR} \
    -e KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR} \
    -e KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR} \
    -e KAFKA_LOG_DIRS=${KAFKA_LOG_DIRS} \
    -e KAFKA_PROCESS_ROLES=${KAFKA_PROCESS_ROLES} \
    -e KAFKA_CONTROLLER_QUORUM_VOTERS=${KAFKA_CONTROLLER_QUORUM_VOTERS} \
    -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} \
    -e KAFKA_INTER_BROKER_LISTENER_NAME=${KAFKA_INTER_BROKER_LISTENER_NAME} \
    -v kafka-data:/var/lib/kafka/data \
    apache/kafka:3.7.2

